# Generated by Django 5.0 on 2025-03-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('renter', 'Ijarachi'), ('owner', 'Ijara Beruvchi')], default='renter', max_length=10),
        ),
    ]
