# Generated by Django 5.0 on 2025-03-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_category_listing_latitude_listing_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='listing_images/'),
        ),
    ]
