# Generated by Django 5.0 on 2025-03-22 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
